### PR TITLE
support geojson in routingCallback and keep feature.properties

### PR DESCRIPTION
**Pull request by schmic**
Hey, found your project, started to use it and miss a thing.

I'm using the BRouter backend for routing which returns geojson.

With that PR I try to propose two things:
a) support geojson, I made a quick shot here to recognize if it (might) be geojson
b) transport additional information from that geojson

I don't except to get this PR merged but maybe want to start a discussing about how to support this.

Cheers, Michael

### CODE REVIEW

**Comment by tmuguet** [comment]
Hi Michael,

Thanks for your contribution! I'd be really interested in merging this PR, I just need to take a closer look at this.

For testing purposes, do you mind providing me a sample of the data you're passing to the `done` callback of `routingCallback`?

Thanks,
Thomas

**Comment by schmic** [comment]
The format is geojson, https://en.wikipedia.org/wiki/GeoJSON

I use BRouter to generate it for a route. I have an example attached.
[brouter.geojson.zip](https://github.com/tmuguet/Leaflet.TrackDrawer/files/4796630/brouter.geojson.zip)

As I said I just wanted to start a discussing on how (and where) to transport the additional information produced by brouter, cause I'd need it later inside my app.

Greetings,
 Michael

PS: You should move that part of code into a separate function cause it's duplicated six (?) times in your code ;-)

**Comment by tmuguet** [comment]
Thanks for the sample GeoJSON file, that will really help.

I'll take a closer look next week and keep you posted.
Anyways my first impression is that some work is also required in `getState` and `restoreState` methods to support undo/redo (otherwise the additional information get lost), and in `toGeoJSON` (to have the addition information exported when exporting the track). I can take care of it, no big deal.

Thanks,
Thomas

**Comment by tmuguet** [comment]
Hi @schmic ,

I started working on the metadata/feature.properties part, it requires a bit of work to transport them to `toGeoJSON` and other methods to have them in your app.

About the GeoJSON format itself, adding its support directly in `routingCallback` callback may not be the best idea because it adds a lot of complexity to handle all cases. IMO, the best way to deal with GeoJSON would be:

- adding support of metadata in the `routingCallback` callback (e.g. `done(err: null | Routing.IError, result: LatLng[], metadata: Object)`)
- converting the GeoJSON into an array of LatLng in your app
- pass the metadata and the array in the callback of your implementation of `routingCallback`

Would that be OK for you?

**Comment by schmic** [comment]
Good morning @tmuguet,

yes I think I could work with that.
For me it's important that I don't have to take care of what Edge belongs to what metadata in my app. I want to keep that complexity out of my routingCallback.

Go for it.

**Comment by tmuguet** [comment]
Hi @schmic ,

I have not forgotten about this feature request but unfortunately I am super busy at work and had no time to fully implement this feature. Keeping metadata synced with the edges in the serialized data is harder than I thought.
Hopefully I'll have some time next week to finish this.

Thanks,
Thomas

**Comment by tmuguet** [comment]
Hi @schmic ,

I hope this is not coming too late, but I finally implemented your request! 

Majors changes are:
* You can provide metadatas in the [routingCallback](https://github.com/tmuguet/Leaflet.TrackDrawer/blob/master/docs/modules/_leaflet_.trackdrawer.md#routingcallback)
* You can provide metadatas when creating [nodes](https://github.com/tmuguet/Leaflet.TrackDrawer/blob/master/docs/interfaces/_leaflet_.trackdrawer.nodeoptions.md)
* `toGeoJSON` and `getState` both give back the metadatas corresponding to nodes and edges
* Added `refreshEdges` as in your PR

Please let me know if you have any feedback.

**Comment by schmic** [comment]
@tmuguet Thanks for the implementation, I'll check it out as soon as I find some time myself during all those holidays. ;-)

**Pull request closed without merging**
